### ISSUE TITLE
Numbering stops at 39

### ISSUE THREAD

**Issue by DutchPete** [onlyafly/header-numbering-obsidian#3]
I have a note with perhaps 50 headers (I have not counted them), but when I activate the plug-in to add numbers, it stops at 39. Could this be fixed?

**Comment by onlyafly** [comment]
Hi @DutchPete: I've tried reproducing this bug, but it seems to work okay for me. Can you send attach an example document where it doesn't work correctly?

**Comment by DutchPete** [comment]
I only have 1 long file like that, but it contains some sensitive info. I would send it to you directly but I see you are on Gmail so I don't want to use that route either.

Although some of my files might grow to more than 39 headers, I'll live with the limitation for now since it only affects 1 file.

**Comment by onlyafly** [comment]
Fixed this issue in version 1.4.1
