### ISSUE TITLE
Version 1.3.0 does not work

### ISSUE THREAD

**Issue by DutchPete** [onlyafly/header-numbering-obsidian#4]
I installed version 1.3.0, refreshed Obsidian, activate the plug-in, then get this on my screen:

![image](https://user-images.githubusercontent.com/10794265/128799284-52a61317-ffb0-496b-b8b7-5cf6d927b332.png)

But the headings are not numbered.

I reinstalled version 1.0.1, that worked. But when I reinstalled 1.3.0 that still does not work, then reinstalled 1.0.1 it did not work anymore either.

BTW, I am on MacOS.

**Comment by DutchPete** [comment]
My apologies. 1.3.0 works now, as did 1.0.1.

**Comment by DutchPete** [comment]
Hmmm, I don't know what's happening, it does NOT work again.

**Comment by onlyafly** [comment]
Seems to work fine for me. Sounds like a reloading issue. I'll continue testing though and see if I can fix it.

**Comment by onlyafly** [comment]
Try version 1.4.0, where I made some bug fixes!
