### ISSUE TITLE
Version 1.3.0 does not automatically renumber

### ISSUE THREAD

**Issue by DutchPete** [onlyafly/header-numbering-obsidian#5]
I don't know if we mean the same thing when we talk about automatic renumbering.

If  I have header A numbered as 1 and I have header B numbered as 2, and I insert a new header between A and B, then it should automatically number the new header as 2 and header B as 3.

That is how I understand it. Right now I still need to press my hotkey to get the numbers reset.

**Comment by onlyafly** [comment]
Hey @DutchPete: It should work. But you need to add "header-numbering-auto: true" to your document's front matter. See the settings screen for details. I'm going to work on improving the experience and documentation on this.

**Comment by DutchPete** [comment]
You mean like so at the top of my note:

```
---
header-numbering-auto: true
---
```

BTW, the Settings screen just shows this:

![image](https://user-images.githubusercontent.com/10794265/128828626-0c4f9207-e700-4b7e-b919-eac7aaa12606.png)

**Comment by DutchPete** [comment]
There is definitely a reloading issue, because when I press ⌘+R Obsidian disappears, and that is only since I installed 1.3.0.

Also, I cannot get 1.3.0 to add numbering to an unnumbered note anymore.

**Comment by DutchPete** [comment]
Another question: is there a way to set "header-numbering-auto: true" vault-wide, rather than on a per note basis?

**Comment by onlyafly** [comment]
Check out version 1.4.0 now. I made it easier to add the front matter settings, and fixed some small bugs. I hope this fixes your issue.
