### ISSUE TITLE
header-numbering-skip-top-level: false

### ISSUE THREAD

**Issue by DutchPete** [onlyafly/header-numbering-obsidian#7]
I assume that this setting at “false” means that h1 headers WILL be counted. If I am right, then it does not work.

Note: the 1st time I used 1.4.0 and got the dialogue box with the question if I wanted to save those settings to the note's front matter I clicked on “yes”. In that dialogue the setting was set to “true”.

So, perhaps it has something to do with a cache? If so, please advise.
If cache clearance is an issue, it should be done automatically by the plug-in, right?

Edit: I went to ~/Library/Application Support/obsidian/Cache, deleted everything in there, refreshed, deleted numbers from headers, and tried again: no change.

BTW, after removing the numbers, then refreshing Obsidian, puts the numbers back. Cache issue.

**Comment by onlyafly** [comment]
Fixed this issue in version 1.4.1
